### PR TITLE
added troubleshooting link for poetry cuda

### PR DESCRIPTION
**Pull request by valerdi**

### CODE REVIEW

**Comment by shiba24** [comment]
If you are using python 3.8 or higher, just changing https://github.com/tub-rip/event_based_optical_flow/blob/main/pyproject.toml#L10 to 
```
torch =  ">=2.0.0"
```
might work, both for CUDA-enabled and CPU-based platforms.

**Comment by valerdi** [comment]
I tried before but it didn't work out for me.  I have a Ubuntu 22.04 and Python 3.10.12. 

I will give it another try with torch = ">= 2.0.0" from scratch and report back.

**Comment by shiba24** [comment]
Thank you for double checking. Let me know if it works.
This is a known issue and related to [6409](https://github.com/python-poetry/poetry/issues/6409) and [76557](https://github.com/pytorch/pytorch/issues/76557).

**Comment by valerdi** [comment]
I got the following error with torch = ">= 2.0.0" 

OSError: libcurand.so.10: cannot open shared object file: No such file or directory

So I went to [6409](https://github.com/python-poetry/poetry/issues/6409) to solve my specific case, that's why I thought to add a line into the install instructions for people who does not know poetry (like me before)

**Comment by shiba24** [comment]
OK. I remember in another project of mine the 2.0.0 worked. But maybe not always true for different settings.

Anyways, thans for the PR. Lmk if there is any other problem.

**Review by shiba24 — APPROVED** [review]

**Pull request merged**
